# Generated by Django 5.1.3 on 2024-12-01 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
                ('artist', models.TextField(max_length=100)),
                ('image', models.ImageField(upload_to='images')),
                ('audio_file', models.FileField(upload_to='audio')),
                ('audio_link', models.CharField(blank=True, max_length=200, null=True)),
                ('duration', models.CharField(max_length=20)),
                ('lyrics', models.TextField()),
            ],
        ),
    ]
